CREATE TABLE [dbo].[Items]
(
    [Id] INT NOT NULL PRIMARY KEY IDENTITY,
    [Name] NVARCHAR(100) NOT NULL,
    [Code] NVARCHAR(50) NOT NULL UNIQUE,
    [Brand] NVARCHAR(50) NOT NULL,
    [UnitPrice] DECIMAL(10,2) NOT NULL
)